#include <stdio.h>
#include <sys/stat.h>

// Макрос для кроссплатформенного создания директорий
#ifdef _WIN32
    #define sys_mkdir(dir) mkdir(dir)
#else
    #define sys_mkdir(dir) mkdir(dir, 0777)
#endif

void create_base_metafiles(const char *lang_name) {
    FILE *git = fopen(".gitignore", "w");
    if (git) {
        fprintf(git, ".DS_Store\n.idea/\n.vscode/\nbuild/\nbin/\nobj/\nout/\n");
        fclose(git);
    }
    FILE *readme = fopen("README.md", "w");
    if (readme) {
        fprintf(readme, "# Project in %s\n\nGenerated by your custom CLI tool.\n", lang_name);
        fclose(readme);
    }
}

// 1. Python
void create_full_project_python() {
    create_base_metafiles("Python");
    FILE *f = fopen("main.py", "w");
    if (f) {
        fprintf(f, "if __name__ == '__main__':\n    print(\"Hello, World!\")\n");
        fclose(f);
    }
    FILE *req = fopen("requirements.txt", "w");
    if (req) fclose(req);
}

// 2. C
void create_full_project_c() {
    create_base_metafiles("C");
    sys_mkdir("src");
    sys_mkdir("include");

    FILE *f = fopen("src/main.c", "w");
    if (f) {
        fprintf(f, "#include <stdio.h>\n\nint main() {\n    printf(\"Hello, World!\\n\");\n    return 0;\n}\n");
        fclose(f);
    }
    FILE *make = fopen("Makefile", "w");
    if (make) {
        fprintf(make, "all:\n\tgcc src/main.c -Iinclude -o program\n");
        fclose(make);
    }
}

// 3. C++
void create_full_project_cpp() {
    create_base_metafiles("C++");
    sys_mkdir("src");
    sys_mkdir("include");

    FILE *f = fopen("src/main.cpp", "w");
    if (f) {
        fprintf(f, "#include <iostream>\n\nint main() {\n    std::cout << \"Hello, World!\" << std::endl;\n    return 0;\n}\n");
        fclose(f);
    }
    FILE *cmake = fopen("CMakeLists.txt", "w");
    if (cmake) {
        fprintf(cmake,
            "cmake_minimum_required(VERSION 3.10)\n"
            "project(MyCppProject)\n"
            "set(CMAKE_CXX_STANDARD 17)\n"
            "include_directories(include)\n"
            "add_executable(program src/main.cpp)\n"
        );
        fclose(cmake);
    }
}

// 4. Java
void create_full_project_java() {
    create_base_metafiles("Java");
    sys_mkdir("src");
    sys_mkdir("src/main");
    sys_mkdir("src/main/java");

    FILE *f = fopen("src/main/java/Main.java", "w");
    if (f) {
        fprintf(f, "public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}\n");
        fclose(f);
    }
    FILE *pom = fopen("pom.xml", "w");
    if (pom) {
        fprintf(pom, "<project>\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.example</groupId>\n  <artifactId>app</artifactId>\n  <version>1.0</version>\n</project>\n");
        fclose(pom);
    }
}

// 5. Go
void create_full_project_go() {
    create_base_metafiles("Go");
    FILE *f = fopen("main.go", "w");
    if (f) {
        fprintf(f, "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}\n");
        fclose(f);
    }
    FILE *mod = fopen("go.mod", "w");
    if (mod) {
        fprintf(mod, "module my_project\n\ngo 1.21\n");
        fclose(mod);
    }
}

// 6. Rust
void create_full_project_rust() {
    create_base_metafiles("Rust");
    sys_mkdir("src");

    FILE *f = fopen("src/main.rs", "w");
    if (f) {
        fprintf(f, "fn main() {\n    println!(\"Hello, World!\");\n}\n");
        fclose(f);
    }
    FILE *cargo = fopen("Cargo.toml", "w");
    if (cargo) {
        fprintf(cargo, "[package]\nname = \"my_project\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n");
        fclose(cargo);
    }
}

// 7. C#
void create_full_project_csharp() {
    create_base_metafiles("C#");
    FILE *f = fopen("Program.cs", "w");
    if (f) {
        fprintf(f, "Console.WriteLine(\"Hello, World!\");\n");
        fclose(f);
    }
    FILE *csproj = fopen("Project.csproj", "w");
    if (csproj) {
        fprintf(csproj, "<Project Sdk=\"Microsoft.NET.Sdk\">\n  <PropertyGroup>\n    <OutputType>Exe</OutputType>\n    <TargetFramework>net8.0</TargetFramework>\n    <ImplicitUsings>enable</ImplicitUsings>\n  </PropertyGroup>\n</Project>\n");
        fclose(csproj);
    }
}

// 8. JavaScript
void create_full_project_javascript() {
    create_base_metafiles("JavaScript");
    sys_mkdir("src");

    FILE *f = fopen("src/index.js", "w");
    if (f) {
        fprintf(f, "console.log(\"Hello, World!\");\n");
        fclose(f);
    }
    FILE *pkg = fopen("package.json", "w");
    if (pkg) {
        fprintf(pkg, "{\n  \"name\": \"js-project\",\n  \"version\": \"1.0.0\",\n  \"main\": \"src/index.js\"\n}\n");
        fclose(pkg);
    }
}

// 9. TypeScript
void create_full_project_typescript() {
    create_base_metafiles("TypeScript");
    sys_mkdir("src");

    FILE *f = fopen("src/index.ts", "w");
    if (f) {
        fprintf(f, "console.log(\"Hello, World!\");\n");
        fclose(f);
    }
    FILE *pkg = fopen("package.json", "w");
    if (pkg) {
        fprintf(pkg, "{\n  \"name\": \"ts-project\",\n  \"version\": \"1.0.0\",\n  \"main\": \"dist/index.js\"\n}\n");
        fclose(pkg);
    }
    FILE *tsconf = fopen("tsconfig.json", "w");
    if (tsconf) {
        fprintf(tsconf, "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"CommonJS\",\n    \"outDir\": \"./dist\",\n    \"rootDir\": \"./src\"\n  }\n}\n");
        fclose(tsconf);
    }
}

// 10. Kotlin
void create_full_project_kotlin() {
    create_base_metafiles("Kotlin");
    sys_mkdir("src");
    sys_mkdir("src/main");
    sys_mkdir("src/main/kotlin");

    FILE *f = fopen("src/main/kotlin/main.kt", "w");
    if (f) {
        fprintf(f, "fun main() {\n    println(\"Hello, World!\")\n}\n");
        fclose(f);
    }
    FILE *gradle = fopen("build.gradle.kts", "w");
    if (gradle) {
        fprintf(gradle, "plugins {\n    kotlin(\"jvm\") version \"1.9.0\"\n}\n");
        fclose(gradle);
    }
}

// 11. Swift
void create_full_project_swift() {
    create_base_metafiles("Swift");
    sys_mkdir("Sources");

    FILE *f = fopen("Sources/main.swift", "w");
    if (f) {
        fprintf(f, "print(\"Hello, World!\")\n");
        fclose(f);
    }
    FILE *pkg = fopen("Package.swift", "w");
    if (pkg) {
        fprintf(pkg, "// swift-tools-version:5.9\nimport PackageDescription\nlet package = Package(name: \"MySwiftProject\", targets: [.executableTarget(name: \"MySwiftProject\", path: \"Sources\")])\n");
        fclose(pkg);
    }
}
